title: 'Smart Nation: The Way Forward'
remote_theme: opendocsg/opendoc-theme
timezone: Asia/Singapore
repository: opendocsg/opendoc-smartnation-strategy
baseurl: '/opendoc-smartnation-strategy'
server_PROD: https://search.opendoc.sg
server_DEV: https://search-staging.opendoc.sg
section_order:
  - Introduction
  - Digital Government, Digital Economy and Digital Society
  - System Foundations
  - People and Culture
  - Smart Nation Projects
  - Strengthening the academia-industry-Government nexus
  - Make strategic bets in artificial intelligence and other frontier technologies
  - Strengthen Singapore’s collaboration with the international community
  - What Can I Do for Smart Nation?
  - Conclusion
styling_options:
  primary_brand_color: '#c91632'
  logo_path: '/assets/images/smartnation_logo.png'
  opendoc_logo_path: '/assets/images/opendoc_logo.png'
  feedback_url: https://form.gov.sg/forms/govtech/5bf2704a59651c000f397fbb
